- name: Download package signing
  ansible.builtin.get_url:
    url: https://packages.linbit.com/package-signing-pubkey.asc
    dest: /tmp/package-signing-pubkey.asc
    mode: '0644'
- name: Add GPG key
  ansible.builtin.shell: |
    gpg --yes -o /etc/apt/trusted.gpg.d/linbit-keyring.gpg --dearmor \
    /tmp/package-signing-pubkey.asc
    PVERS=9 && echo "deb [signed-by=/etc/apt/trusted.gpg.d/linbit-keyring.gpg] \
    https://packages.linbit.com/public/ proxmox-9 drbd-9" > /etc/apt/sources.list.d/linbit.list
- name: install necessary linstor packages
  apt:
    name: 
    - drbd-dkms
    - drbd-utils
    - linstor-proxmox
    - pve-headers
    - drbd-dkms
    - drbd-utils
    - linstor-controller
    - linstor-satellite
    - linstor-client
    - linstor-common
    - cryptsetup
    update_cache: yes
    state: latest
- name: Install pve headers
  ansible.builtin.shell: |
    apt-mark hold linstor-controller linstor-satellite linstor-client linstor-common
    systemctl enable linstor-satellite --now
    apt install pve-headers-$(uname -r)
    apt -y install --reinstall drbd-dkms drbd-utils
- name: enroll mok key
  ansible.builtin.shell: |
    yes dkms | head -n 2 | mokutil --import /var/lib/dkms/mok.pub
- name: reboot
  ansible.builtin.shell: reboot
  async: 1
  poll: 0
  ignore_errors: yes
- name: Wait for hosts reboot
  ansible.builtin.wait_for_connection:
    timeout: 800
- name: Setup first controller node
  ansible.builtin.shell: |
    systemctl enable linstor-controller --now
    linstor node create slmitstestsrv01 10.49.172.184 --node-type combined
    linstor node create slmitstestsrv02 10.49.172.185 --node-type combined
    linstor node create slmitstestbkp01 10.49.172.186 --node-type combined
  when: inventory_hostname == "proxmox-01" 
- name: Create volume group - node 01
  ansible.builtin.shell: |
    vgcreate datavg /dev/sda
    lvcreate -L 2048GiB -T datavg/proxmox-storage
    lvcreate -L 2048GiB -T datavg/k8s-storage
    lvcreate -L 4096MiB -T datavg/linstor-db
  when: inventory_hostname == "proxmox-01"
- name: Create volume group - node 02
  ansible.builtin.shell: |
    vgcreate datavg /dev/sda
    lvcreate -L 2048GiB -T datavg/proxmox-storage
    lvcreate -L 2048GiB -T datavg/k8s-storage
    lvcreate -L 4096MiB -T datavg/linstor-db
  when: inventory_hostname == "proxmox-02"
- name: Create volume group - backup node
  ansible.builtin.shell: |
    vgcreate datavg /dev/sda
    lvcreate -L 4096MiB -T datavg/linstor-db
    lvcreate -L 6144GiB -T datavg/backup-storage
  when: inventory_hostname == "proxmox-03"
- name: replace encrypt block
  replace:
    path: /etc/linstor/linstor.toml
    regexp: '\[encrypt\]'
    replace: ''
- name: Update LUKS key
  ansible.builtin.blockinfile:
    path: /etc/linstor/linstor.toml
    append_newline: true
    prepend_newline: true
    block: |
      [encrypt]
      passphrase={{ master_key }}
  
- name: Create linstor storage pools on the nodes
  ansible.builtin.shell: |
    linstor storage-pool create lvmthin slmitstestsrv01 proxmox-storage datavg/proxmox-storage
    linstor storage-pool create lvmthin slmitstestsrv02 proxmox-storage datavg/proxmox-storage
    linstor resource-group create proxmox-storage --storage-pool=proxmox-storage --place-count=2 -l DRBD,LUKS,STORAGE
    linstor storage-pool create lvmthin slmitstestsrv01 k8s-storage datavg/k8s-storage
    linstor storage-pool create lvmthin slmitstestsrv02 k8s-storage datavg/k8s-storage
    linstor resource-group create k8s-storage --storage-pool=k8s-storage --place-count=2 -l DRBD,LUKS,STORAGE
    linstor storage-pool create lvmthin slmitstestsrv01 linstor-db datavg/linstor-db
    linstor storage-pool create lvmthin slmitstestsrv02 linstor-db datavg/linstor-db
    linstor storage-pool create lvmthin slmitstestbkp01 linstor-db datavg/linstor-db
    linstor resource-group create linstor-db --storage-pool=linstor-db --place-count=3 -l DRBD,LUKS,STORAGE
  when: inventory_hostname == "proxmox-01" 

- name: HA Controller
  ansible.builtin.shell: |
    linstor resource-definition create linstor_db -l DRBD,LUKS,STORAGE --storage-pool linstor-db
    linstor rd drbd-options --auto-promote=no linstor_db
    linstor rd drbd-options --quorum=majority linstor_db
    linstor rd drbd-options --on-suspended-primary-outdated=force-secondary linstor_db
    linstor rd drbd-options --on-no-quorum=io-error linstor_db
    linstor rd drbd-options --on-no-data-accessible=io-error linstor_db
    linstor rd drbd-options --rr-conflict=retry-connect linstor_db
    linstor volume-definition create linstor_db 2G
    linstor resource create linstor_db --storage-pool linstor-db --auto-place 3
    systemctl disable --now linstor-controller
- name: create mount file for linstor controllers
  ansible.builtin.shell: |
    cat << EOF > /etc/systemd/system/var-lib-linstor.mount
    [Unit]
    Description=Filesystem for the LINSTOR controller

    [Mount]
    # you can use the minor like /dev/drbdX or the udev symlink
    What=/dev/drbd/by-res/linstor_db/0
    Where=/var/lib/linstor
    EOF
  
- name: copy linstor db file
  ansible.builtin.shell: |
    mv /var/lib/linstor{,.orig}
    mkdir /var/lib/linstor
    chattr -i /var/lib/linstor
    drbdadm primary linstor_db
    mkfs.ext4 /dev/drbd/by-res/linstor_db/0
    systemctl start var-lib-linstor.mount
    cp -r /var/lib/linstor.orig/* /var/lib/linstor
    systemctl start linstor-controller
  when: inventory_hostname == "proxmox-01" 
- name: install drbd-reactor
  apt:
    name: 
    - drbd-reactor
    update_cache: yes
    state: latest
- name: disable linstor-controller service
  ansible.builtin.shell: |
    systemctl disable linstor-controller
    chattr +i /var/lib/linstor
- name: create drbd-reactor file for linstor controllers
  ansible.builtin.shell: |
    cat << EOF > /etc/drbd-reactor.d/linstor_db.toml
    [[promoter]]
    id = "linstor_db"
    [promoter.resources.linstor_db]
    start = ["var-lib-linstor.mount","linstor-controller.service"]
    on-drbd-demote-failure = "reboot"
    secondary-force = true
    EOF
    systemctl restart drbd-reactor
    systemctl enable drbd-reactor
  
- name: ensure override folder exists
  file:
    path: /etc/systemd/system/linstor-satellite.service.d
    state: directory
- name: Edit satellite service
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/linstor-satellite.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
- name: restart linstor-satellite service
  ansible.builtin.shell: |
    systemctl restart linstor-satellite
- name: Configure storage
  ansible.builtin.template:
    src: storage.cfg.j2
    dest: /etc/pve/storage.cfg
    owner: root
    group: www-data
    mode: '0640'
