- name: Create a Proxmox VE Cluster
  community.proxmox.proxmox_cluster:
    state: present
    api_host: "{{ proxmox_01_api }}"
    api_user: "{{ root_user }}"
    api_password: "{{ root_secret_01 }}"
    validate_certs: false
    link0: "{{ proxmox_01_link0 }}"
    link1: "{{ proxmox_01_link1 }}"
    cluster_name: "{{ cluster_name }}"

